services:
  # Base de données PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: master_annonce_db
    environment:
      POSTGRES_DB: master_annonce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Je laisse ton init.sql s'il existe toujours dans ton projet
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    # INDISPENSABLE : Vérifie que la BDD est prête
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Application Spring Boot
  app:
    build: .
    container_name: master_annonce_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        # On attend que le healthcheck de la DB soit OK avant de lancer l'app
        condition: service_healthy
    environment:
      # Variables qui correspondent à ton application.yml
      DATABASE_URL: jdbc:postgresql://db:5432/master_annonce
      DB_USER: postgres
      DB_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
