-- Script d'initialisation de la base de données MasterAnnonce
-- Laisser Hibernate gérer la création du schéma via hbm2ddl.auto
-- CREATE TABLE IF NOT EXISTS annonce (
--    id SERIAL PRIMARY KEY,
--    title VARCHAR(64),
--    description VARCHAR(256),
--    adress VARCHAR(64),
--    mail VARCHAR(64),
--    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
